"use client";
import {useEffect,useRef,useState} from "react";
import {GraduationCap,CalendarDays,BellRing,Inbox,ClipboardCheck,SlidersHorizontal,CircleHelp,LoaderCircle,Sparkles,ShieldCheck,ExternalLink,Download,RefreshCw,EyeOff,Eye,Radar,Trash2,Play,Check,Copy,Lock,KeyRound,Link2} from "lucide-react";
import {Switch} from "@/components/ui/switch";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import type {Settings,Digest,Deadline,MonitorInfo} from "@/lib/types";
import {buildIcs} from "@/lib/ics";
import {digestMarkdown} from "@/lib/digest-export";
const initial:Settings={canvasUrl:"https://canvas.auckland.ac.nz",feedUrl:"",profileId:"",days:7,tasks:{todo:true,grades:true,announcements:true,inbox:false}};
type Health={serverKey:boolean;canvasUrl:string;feedConfigured:boolean;profileConfigured:boolean};
function dayLabel(iso:string){const d=new Date(iso);if(isNaN(d.getTime()))return {b:"—",s:iso.slice(0,10),cls:""};const today=new Date();const diff=Math.floor((new Date(d.toDateString()).getTime()-new Date(today.toDateString()).getTime())/86400e3);return {b:String(d.getDate()),s:d.toLocaleString("en-NZ",{month:"short"}),cls:diff<0?"late":diff===0?"today":""}}
function timeLabel(iso:string){const d=new Date(iso);return isNaN(d.getTime())?iso:d.toLocaleString("en-NZ",{weekday:"short",hour:"2-digit",minute:"2-digit"})}
function download(name:string,type:string,content:string){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}

export default function Home(){
 const [s,setS]=useState<Settings>(initial),[digest,setDigest]=useState<Digest|null>(null),[busy,setBusy]=useState(false),[phase,setPhase]=useState(""),[error,setError]=useState(""),[help,setHelp]=useState(false),[view,setView]=useState("due"),[apiKey,setApiKey]=useState(""),[ready,setReady]=useState(false),[blur,setBlur]=useState(false),[health,setHealth]=useState<Health|null>(null),[copied,setCopied]=useState(false);
 const [monitors,setMonitors]=useState<MonitorInfo[]>([]),[cron,setCron]=useState("CRON_TZ=Pacific/Auckland 0 7 * * *"),[webhook,setWebhook]=useState(""),[monitorBusy,setMonitorBusy]=useState(false),[monitorMsg,setMonitorMsg]=useState("");
 const abort=useRef<AbortController|null>(null),busyRef=useRef(false);
 const headers=()=>({"Content-Type":"application/json",...(apiKey?{"x-tinyfish-api-key":apiKey}:{})});
 useEffect(()=>{try{const p=localStorage.getItem("canvaspilot-settings"),d=localStorage.getItem("canvaspilot-last"),k=localStorage.getItem("canvaspilot-api-key"),w=localStorage.getItem("canvaspilot-webhook");if(p)setS({...initial,...JSON.parse(p),tasks:{...initial.tasks,...(JSON.parse(p).tasks||{})}});if(d)setDigest(JSON.parse(d));if(k)setApiKey(k);if(w)setWebhook(w)}catch{}setReady(true);fetch("/api/health").then(r=>r.json()).then((h:Health)=>{setHealth(h);if(h.canvasUrl)setS(prev=>prev.canvasUrl===initial.canvasUrl?{...prev,canvasUrl:h.canvasUrl}:prev)}).catch(()=>{})},[]);
 useEffect(()=>{if(ready)localStorage.setItem("canvaspilot-settings",JSON.stringify(s))},[s,ready]);
 useEffect(()=>{if(ready)localStorage.setItem("canvaspilot-api-key",apiKey)},[apiKey,ready]);
 useEffect(()=>{if(ready)localStorage.setItem("canvaspilot-webhook",webhook)},[webhook,ready]);
 function update<K extends keyof Settings>(key:K,value:Settings[K]){setS(p=>({...p,[key]:value}))}
 function task(key:keyof Settings["tasks"],value:boolean){setS(p=>({...p,tasks:{...p.tasks,[key]:value}}))}
 async function run(){if(busyRef.current)return;busyRef.current=true;setBusy(true);setError("");setPhase("Starting…");const controller=new AbortController();abort.current=controller;
  try{const response=await fetch("/api/digest",{method:"POST",headers:headers(),body:JSON.stringify(s),signal:controller.signal});if(!response.ok)throw new Error(((await response.json()) as {error?:string}).error||"The digest could not start.");if(!response.body)throw new Error("The connection did not open.");
   const reader=response.body.getReader();const decoder=new TextDecoder();let pending="",finished=false;
   while(true){const {done,value}=await reader.read();if(done)break;pending+=decoder.decode(value,{stream:true});const lines=pending.split("\n");pending=lines.pop()||"";for(const line of lines){if(!line.trim())continue;const event=JSON.parse(line);if(event.type==="progress")setPhase(event.message);if(event.type==="error")throw new Error(event.message);if(event.type==="result"){setDigest(event.data);localStorage.setItem("canvaspilot-last",JSON.stringify(event.data));finished=true;setView("due")}}}
   if(!finished)throw new Error("Connection ended before the digest finished. The previous digest is kept.");
  }catch(e){setError(e instanceof Error?(e.name==="AbortError"?"Stopped. The previous digest is kept.":e.message):"Something went wrong.")}finally{setBusy(false);busyRef.current=false;setPhase("")}}
 async function loadMonitors(){try{const r=await fetch("/api/monitor",{headers:headers()});const j=await r.json();if(r.ok)setMonitors(j.monitors||[]);else setMonitorMsg(j.error||"")}catch{}}
 useEffect(()=>{if(view==="monitor")void loadMonitors()},[view]); // eslint-disable-line react-hooks/exhaustive-deps
 async function createMonitor(){setMonitorBusy(true);setMonitorMsg("");try{const r=await fetch("/api/monitor",{method:"POST",headers:headers(),body:JSON.stringify({feedUrl:s.feedUrl,cron,webhook:webhook||undefined})});const j=await r.json();if(!r.ok)throw new Error(j.error);setMonitorMsg("Monitor created. TinyFish took a baseline of your feed and will re-read it on schedule.");await loadMonitors()}catch(e){setMonitorMsg(e instanceof Error?e.message:"Could not create the monitor.")}finally{setMonitorBusy(false)}}
 async function monitorAction(id:string,method:"PUT"|"DELETE"){setMonitorBusy(true);setMonitorMsg("");try{const r=await fetch(`/api/monitor?id=${encodeURIComponent(id)}`,{method,headers:headers()});const j=await r.json();if(!r.ok)throw new Error(j.error);setMonitorMsg(method==="PUT"?`Ran now: ${j.run?.results?.length||0} result(s), ${j.run?.errors?.length||0} error(s).`:"Monitor deleted.");await loadMonitors()}catch(e){setMonitorMsg(e instanceof Error?e.message:"Monitor action failed.")}finally{setMonitorBusy(false)}}
 async function copyMarkdown(){if(!digest)return;try{await navigator.clipboard.writeText(digestMarkdown(digest));setCopied(true);setTimeout(()=>setCopied(false),1600)}catch{download("canvas-digest.md","text/markdown",digestMarkdown(digest))}}
 const dl=digest?.deadlines||[];const today=dl.filter(d=>dayLabel(d.due).cls==="today"),late=dl.filter(d=>d.status==="missing"||dayLabel(d.due).cls==="late");
 const groups:[string,Deadline[]][]=[["OVERDUE / MISSING",late],["DUE TODAY",today.filter(d=>!late.includes(d))],["COMING UP",dl.filter(d=>!late.includes(d)&&!today.includes(d))]];
 const checked=digest?new Date(digest.generatedAt).toLocaleString("en-NZ",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}):null;
 const keyOk=!!apiKey||!!health?.serverKey;
 return <div className={"app-shell"+(blur?" blur":"")}><header className="topbar"><a className="brand" href="/"><span className="brand-icon"><GraduationCap size={21}/></span>canvaspilot<span className="brand-period">.</span></a><span className="top-label">YOUR WEEK, ALREADY READ</span><div className="top-actions"><button className="icon-button" onClick={()=>setBlur(!blur)} aria-label={blur?"Show personal details":"Blur personal details"} title={blur?"Show personal details":"Blur personal details for recordings"}>{blur?<EyeOff size={20}/>:<Eye size={20}/>}</button><button className="icon-button" onClick={()=>setHelp(!help)} aria-label="How CanvasPilot works"><CircleHelp size={21}/></button><a href="https://github.com/Chethan-4255/canvaspilot_tinyfish.ai" target="_blank" rel="noopener noreferrer" className="icon-button" aria-label="GitHub Repository"><svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 .5a12 12 0 0 0-3.8 23.4c.6.1.8-.3.8-.6v-2.2c-3.3.7-4-1.4-4-1.4-.5-1.4-1.3-1.8-1.3-1.8-1.1-.7.1-.7.1-.7 1.2.1 1.8 1.2 1.8 1.2 1.1 1.8 2.8 1.3 3.5 1 .1-.8.4-1.3.8-1.6-2.7-.3-5.5-1.3-5.5-5.9 0-1.3.5-2.4 1.2-3.2-.1-.3-.5-1.5.1-3.2 0 0 1-.3 3.3 1.2a11.5 11.5 0 0 1 6 0C17.3 4.7 18.3 5 18.3 5c.7 1.7.3 2.9.1 3.2.8.8 1.2 1.9 1.2 3.2 0 4.6-2.8 5.6-5.5 5.9.4.4.8 1.1.8 2.2v3.3c0 .3.2.7.8.6A12 12 0 0 0 12 .5z"/></svg></a></div></header>
 <div className="workspace"><aside className="sidebar"><div className="aside-heading"><SlidersHorizontal size={18}/><h2>Your Canvas</h2></div><p className="muted intro-small">Read-only. Nothing gets submitted or marked as read.</p><form onSubmit={e=>{e.preventDefault();void run()}}>
 <label htmlFor="canvasUrl">Canvas address</label><input id="canvasUrl" required maxLength={200} value={s.canvasUrl} onChange={e=>update("canvasUrl",e.target.value)} placeholder="https://canvas.youruni.ac.nz"/>
 <label htmlFor="days">Look ahead</label><select id="days" value={s.days} onChange={e=>update("days",Number(e.target.value))}>{[3,7,14,21,30].map(n=><option key={n} value={n}>{n} days</option>)}</select>
 <label className="block">What to collect</label>
 <div className="switch-row"><label htmlFor="t-todo">To-do & due dates<small>Dashboard to-do list and agenda</small></label><Switch id="t-todo" checked={s.tasks.todo} onCheckedChange={v=>task("todo",v)}/></div>
 <div className="switch-row"><label htmlFor="t-grades">New grades & feedback<small>Opens instructor comments</small></label><Switch id="t-grades" checked={s.tasks.grades} onCheckedChange={v=>task("grades",v)}/></div>
 <div className="switch-row"><label htmlFor="t-ann">Announcements<small>Last 7 days, all courses</small></label><Switch id="t-ann" checked={s.tasks.announcements} onCheckedChange={v=>task("announcements",v)}/></div>
 <div className="switch-row"><label htmlFor="t-inbox">Inbox<small>Unread conversations</small></label><Switch id="t-inbox" checked={s.tasks.inbox} onCheckedChange={v=>task("inbox",v)}/></div>
 <details className="source-input" open={!s.feedUrl&&!health?.feedConfigured}><summary><Link2 size={14} style={{display:"inline",verticalAlign:"-2px",marginRight:6}}/>Calendar feed (no login needed)</summary><label className="sr-only" htmlFor="feedUrl">Canvas calendar feed URL</label><input id="feedUrl" type="url" maxLength={600} value={s.feedUrl} onChange={e=>update("feedUrl",e.target.value)} placeholder={health?.feedConfigured?"Using the feed configured on the server":"https://canvas…/feeds/calendars/user_….ics"}/><p className="field-note">In Canvas open <b>Calendar → Calendar Feed</b> and paste the link. TinyFish Fetch reads it live for exact due times and it powers the daily monitor. It stays in this browser.</p></details>
 <details className="source-input"><summary><Lock size={14} style={{display:"inline",verticalAlign:"-2px",marginRight:6}}/>Browser profile (signed-in session)</summary><label className="sr-only" htmlFor="profileId">TinyFish Browser Context Profile ID</label><input id="profileId" maxLength={120} value={s.profileId} onChange={e=>update("profileId",e.target.value)} placeholder={health?.profileConfigured?"Using the profile configured on the server":"Optional: profile id, else your default profile"}/><p className="field-note">Sign in to Canvas once inside <a href="https://agent.tinyfish.ai/" target="_blank" rel="noopener noreferrer">TinyFish → Browser Context Profiles</a>. The agent reuses that session. Your password never touches this app.</p></details>
 <details className="source-input"><summary><KeyRound size={14} style={{display:"inline",verticalAlign:"-2px",marginRight:6}}/>API Key Settings</summary><label className="sr-only" htmlFor="apiKey">TinyFish API Key</label><input type="password" id="apiKey" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="tf_..." autoComplete="off"/><p className="field-note">Optional. Kept in this browser's storage; otherwise the server key is used.</p></details>
 <button className="primary run-button" type="submit" disabled={busy||!keyOk}>{busy?<LoaderCircle className="spin" size={18}/>:<Sparkles size={18}/>} {busy?"Reading Canvas…":"Build my digest"}</button>{!keyOk&&health&&<p className="field-note">Add a TinyFish API key to start.</p>}</form>
 <div className="privacy-note"><ShieldCheck size={17}/><p>Only your own account, read-only, inside your university's rules. Digests stay in this browser.</p></div><a href="https://www.tinyfish.ai/" target="_blank" rel="noopener noreferrer" className="powered"><span className="tinyfish-mark">≈</span><div>Live web, powered by<br/><strong>TinyFish</strong></div></a></aside>
 <main className="main"><div className="page-heading"><div><div className="eyebrow">ONE RUN. WHOLE WEEK.</div><h1>Canvas, already read<span>.</span></h1><p>What's due, what got graded, what your lecturers posted. No tabs.</p></div><div className="heading-art" aria-hidden="true"><span/><span/><span/><span/></div></div>
 <div className="status-strip"><div><Radar size={18}/><span>{busy?phase:checked?`Last digest ${checked}${digest?.student?` · ${digest.student}`:""}`:"Ready to read your Canvas"}</span></div><label><Switch id="blur" checked={blur} onCheckedChange={setBlur}/> Blur names & scores for recording</label></div>
 {busy&&<div className="progress" role="status"><span className="progress-line"/><p>{phase}</p><button className="text-button" onClick={()=>abort.current?.abort()}>Stop</button></div>}{error&&<div className="error" role="alert">{error}</div>}
 {help&&<section className="how-panel"><h2>How CanvasPilot uses TinyFish</h2><div className="how-grid"><p><b>01 / Agent</b>Opens your Canvas inside the browser session you saved as a TinyFish Browser Context Profile, walks the dashboard, grades pages, announcements and inbox, and returns structured data. Read-only by instruction and never leaves your Canvas domain.</p><p><b>02 / Fetch</b>Reads your private Canvas calendar feed (.ics) live for exact due timestamps. No login, no cache (<code>ttl: 0</code>), and it's merged with the agent's submission status.</p><p><b>03 / Monitor</b>A TinyFish page monitor re-reads that feed on a cron schedule and posts to your webhook when deadlines appear, move or vanish.</p></div><h2 style={{fontSize:16,marginTop:18}}>One-time setup</h2><ol><li>Create a TinyFish API key and add it in Settings (or on the server).</li><li>In TinyFish, open <b>Browser Context Profiles → Create Profile → Create and set up</b>, sign in to Canvas (SSO and MFA are fine), then save. Optionally paste the profile id in the sidebar.</li><li>In Canvas, open <b>Calendar → Calendar Feed</b> and paste the link in the sidebar.</li></ol></section>}
 {digest&&<div className="summary-row"><div className={"summary-card"+(late.length?" alert":"")}><strong>{late.length}</strong><span>overdue or missing</span></div><div className="summary-card"><strong>{dl.length}</strong><span>due in {s.days} days</span></div><div className="summary-card"><strong>{digest.grades.length}</strong><span>new grades</span></div><div className="summary-card"><strong>{digest.announcements.length}</strong><span>announcements</span></div></div>}
 <div className="results-heading"><Tabs value={view} onValueChange={setView}><TabsList variant="line"><TabsTrigger value="due"><CalendarDays size={15}/> Due <span className="count">{dl.length}</span></TabsTrigger><TabsTrigger value="grades"><ClipboardCheck size={15}/> Grades <span className="count">{digest?.grades.length||0}</span></TabsTrigger><TabsTrigger value="news"><BellRing size={15}/> Announcements <span className="count">{digest?.announcements.length||0}</span></TabsTrigger><TabsTrigger value="inbox"><Inbox size={15}/> Inbox <span className="count">{digest?.inbox.length||0}</span></TabsTrigger><TabsTrigger value="monitor"><Radar size={15}/> Monitor</TabsTrigger></TabsList></Tabs>
 {digest&&view!=="monitor"&&<div className="export-bar"><button className="secondary" onClick={()=>download("canvas-deadlines.ics","text/calendar",buildIcs(dl))} disabled={!dl.length}><Download size={15}/> Add to calendar (.ics)</button><button className="secondary" onClick={copyMarkdown}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?"Copied":"Copy digest"}</button><button className="secondary" onClick={()=>download("canvas-digest.json","application/json",JSON.stringify(digest,null,2))}><Download size={15}/> JSON</button><button className="icon-button" disabled={busy} aria-label="Refresh digest" onClick={()=>void run()}><RefreshCw size={18}/></button></div>}</div>
 {digest&&view!=="monitor"&&<div className="run-summary"><span>{digest.sources.join(" + ")||"no sources read"}</span><span>Fetch {digest.calls.fetch} · Agent {digest.calls.agent}</span>{digest.runId&&<span>run {digest.runId.slice(0,8)}…</span>}</div>}
 {!digest&&!busy&&view!=="monitor"&&<section className="start-state"><div className="start-icon"><GraduationCap size={30}/></div><h2>Set it up once. Use it every Monday.</h2><p>CanvasPilot signs in with the browser session you saved, reads what's due, what got graded and what was announced,<br/>then hands you a digest and a calendar file.</p><div className="setup-steps"><div><b><Lock size={15}/> 1 · Save a session</b><p>In <a href="https://agent.tinyfish.ai/" target="_blank" rel="noopener noreferrer">TinyFish</a> → Browser Context Profiles, create a profile and sign in to Canvas yourself. Cookies are saved, your password isn't.</p></div><div><b><Link2 size={15}/> 2 · Paste your calendar feed</b><p>Canvas → Calendar → Calendar Feed. Fetch reads it live for exact due times, and Monitor watches it daily.</p></div><div><b><Sparkles size={15}/> 3 · Build the digest</b><p>Pick what to collect and run. Export an .ics for Google or Apple Calendar, or copy the digest into Notion.</p></div></div><div className="trust-strip"><span><ShieldCheck size={16}/> Read-only instructions</span><span><Lock size={16}/> No passwords in the app</span><span><Radar size={16}/> Live Canvas, not a mock</span></div></section>}
 {digest&&view==="due"&&<div>{groups.filter(([,items])=>items.length).map(([title,items])=><div key={title}><div className="group-title">{title}</div><div className="item-list">{items.map(d=>{const l=dayLabel(d.due);return <article className="item" key={d.id}><div className={"date-chip "+l.cls}><b>{l.b}</b><span>{l.s}</span></div><div className="item-body"><div className="item-top">{d.course&&<span className="course-tag sensitive">{d.course}</span>}<span>{timeLabel(d.due)}</span><span className={"pill "+d.status}>{d.status==="due"?"still due":d.status}</span></div><h3>{d.title}</h3><div className="item-meta"><span className="pill source">{d.kind}</span>{d.points&&<span>{d.points}</span>}<span>via {d.source==="calendar"?"calendar feed":"Canvas session"}</span></div></div><a className="open-link" href={d.url} target="_blank" rel="noopener noreferrer">Open <ExternalLink size={13}/></a></article>})}</div></div>)}{!dl.length&&<section className="empty-results"><CalendarDays size={27}/><h2>Nothing due in this window.</h2><p>Try a longer look-ahead, or add your calendar feed so exact due dates come straight from Canvas.</p></section>}</div>}
 {digest&&view==="grades"&&<div className="item-list">{digest.grades.map((g,i)=><article className="item" key={i}><div className="item-body"><div className="item-top"><span className="course-tag sensitive">{g.course}</span>{g.gradedAt&&<span>{g.gradedAt}</span>}</div><h3>{g.assignment}</h3>{g.feedback?<blockquote className="sensitive">{g.feedback}</blockquote>:<p>No written feedback yet.</p>}</div><div className="grade-score sensitive"><strong>{g.score}</strong><span>{g.outOf?`out of ${g.outOf}`:"score"}</span></div>{g.url&&<a className="open-link" href={g.url} target="_blank" rel="noopener noreferrer">Open <ExternalLink size={13}/></a>}</article>)}{!digest.grades.length&&<section className="empty-results"><ClipboardCheck size={27}/><h2>No new grades.</h2><p>Grades posted in the last two weeks show up here with the instructor's comments.</p></section>}</div>}
 {digest&&view==="news"&&<div className="item-list">{digest.announcements.map((a,i)=><article className="item" key={i}><div className="item-body"><div className="item-top"><span className="course-tag sensitive">{a.course}</span>{a.postedAt&&<span>{a.postedAt}</span>}</div><h3>{a.title}</h3><p>{a.summary}</p></div>{a.url&&<a className="open-link" href={a.url} target="_blank" rel="noopener noreferrer">Open <ExternalLink size={13}/></a>}</article>)}{!digest.announcements.length&&<section className="empty-results"><BellRing size={27}/><h2>Quiet week.</h2><p>No announcements in the last 7 days across your courses.</p></section>}</div>}
 {digest&&view==="inbox"&&<div className="item-list">{digest.inbox.map((m,i)=><article className="item" key={i}><div className="item-body"><div className="item-top"><span className="sensitive">{m.from}</span>{m.receivedAt&&<span>{m.receivedAt}</span>}</div><h3>{m.subject}</h3><p className="sensitive">{m.preview}</p></div></article>)}{!digest.inbox.length&&<section className="empty-results"><Inbox size={27}/><h2>Inbox is clear.</h2><p>{s.tasks.inbox?"No unread conversations in the last 7 days.":"Turn on Inbox in the sidebar to include unread conversations."}</p></section>}</div>}
 {view==="monitor"&&<section className="monitor-card"><h3>Watch deadlines while you sleep</h3><p>TinyFish Monitor re-reads your calendar feed on a schedule, compares it with the last run, and posts to your webhook when something is added, moved or removed. Pair it with a Discord or Slack webhook, or Zapier.</p><div className="monitor-form"><div><label htmlFor="cron">Schedule (cron, UTC unless prefixed)</label><input id="cron" value={cron} onChange={e=>setCron(e.target.value)}/></div><div><label htmlFor="webhook">Webhook URL (optional, https)</label><input id="webhook" type="url" value={webhook} onChange={e=>setWebhook(e.target.value)} placeholder="https://hooks.zapier.com/… or Discord webhook"/></div><button className="primary" onClick={createMonitor} disabled={monitorBusy||!keyOk||(!s.feedUrl&&!health?.feedConfigured)}>{monitorBusy?<LoaderCircle className="spin" size={16}/>:<Radar size={16}/>} Create monitor</button></div>{!s.feedUrl&&!health?.feedConfigured&&<p className="field-note">Add your calendar feed in the sidebar first. Monitors only read public URLs, so the feed link is what makes this possible without a login.</p>}{monitorMsg&&<p className="notice" style={{marginTop:12}}>{monitorMsg}</p>}
 <div className="monitor-list">{monitors.map(m=><div className="monitor-row" key={m.id}><div><span className={"pill "+m.status}>{m.status}</span><strong>{m.name}</strong><code>{m.schedule_cron}</code>{m.webhook_url&&<span className="muted">→ webhook</span>}</div><div><button className="secondary" disabled={monitorBusy} onClick={()=>monitorAction(m.id,"PUT")}><Play size={14}/> Run now</button><button className="secondary" disabled={monitorBusy} onClick={()=>monitorAction(m.id,"DELETE")}><Trash2 size={14}/> Delete</button></div></div>)}{!monitors.length&&<p className="field-note">No CanvasPilot monitors yet.</p>}</div></section>}
 {!!digest?.warnings?.length&&view!=="monitor"&&<details className="warnings"><summary>{digest.warnings.length} note{digest.warnings.length>1?"s":""} from this run</summary>{digest.warnings.map((w,i)=><p key={i}>{w}</p>)}</details>}
 {!!digest?.agentSteps?.length&&view!=="monitor"&&<details className="steps"><summary>What the agent did ({digest.agentSteps.length} steps)</summary><ol>{digest.agentSteps.map((st,i)=><li key={i}>{st}</li>)}</ol></details>}
 <footer><span>Made for Monday mornings at uni.</span><button onClick={()=>setHelp(true)}>How it works <CircleHelp size={14}/></button></footer></main></div></div>
}
